theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "music"
player = "spotify"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
