#!/bin/zsh


echo "xinit started: $*; $1"

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

cdir="$(dirname "$0")"

xrdb -merge ~/.Xresources
export QT_QPA_PLATFORMTHEME='gtk3'
export WINIT_HIDPI_FACTOR=1.0

# . /etc/X11/xinit/xinitrc.d/50-systemd-user.sh
# export $(dbus-launch)   # this is a hack. systemd should do it automatically.

case "$1" in
    fluxbox)
        zsh ~/.fluxbox/startup &
        exec fluxbox -log /tmp/fluxbox.log;;
    i3)
        exec i3 -c ~/run/ui/i3/config.i3 -V >> /tmp/i3log-$(date +'%F-%k-%M-%S') 2>&1 ;;
    *) exit 1 ;;
esac

